// AUTO-GENERATED by scripts/generate-motion-endpoint-map.ts — do not edit
// Endpoint ID → generated Zod schema and codec mapping for motion models

import { z } from 'zod';

import { motionTransform } from './motion-transform';

import {
  zGrokImagineVideoImageToVideoInput,
  zKlingVideoV3ProImageToVideoInput,
  zVeo31ImageToVideoInput,
} from './generated/zod.gen';

import {
  GrokImagineVideoImageToVideoInputSchema,
  KlingVideoV3ProImageToVideoInputSchema,
  Veo31ImageToVideoInputSchema,
} from './generated/schemas.gen';

// ---------------------------------------------------------------------------
// Inline schemas for new endpoints not yet in generated files
// ---------------------------------------------------------------------------

export const zLtx23ImageToVideoInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: 'The prompt to use for the generated video',
  }),
  image_url: z.union([z.string(), z.string()]),
  end_image_url: z.union([z.string(), z.unknown()]).optional(),
  duration: z
    .enum(['6', '8', '10'])
    .register(z.globalRegistry, {
      description: 'The duration of the generated video in seconds',
    })
    .optional(),
  aspect_ratio: z
    .enum(['auto', '16:9', '9:16'])
    .register(z.globalRegistry, {
      description:
        "The aspect ratio of the generated video. If 'auto', the aspect ratio will be determined automatically based on the input image.",
    })
    .optional(),
  resolution: z
    .enum(['1080p', '1440p', '2160p'])
    .register(z.globalRegistry, {
      description: 'Output video resolution',
    })
    .optional(),
  fps: z
    .enum(['24', '25', '48', '50'])
    .register(z.globalRegistry, {
      description: 'Frames per second',
    })
    .optional(),
  generate_audio: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether to generate audio for the video',
    })
    .optional()
    .default(true),
  seed: z.union([z.int(), z.unknown()]).optional(),
  negative_prompt: z.union([z.string(), z.unknown()]).optional(),
  num_inference_steps: z
    .union([z.int().gte(1).lte(50), z.unknown()])
    .optional(),
  guidance_scale: z.union([z.number(), z.unknown()]).optional(),
});

export const Ltx23ImageToVideoInputSchema = {
  title: 'LTX23ImageToVideoInput',
  type: 'object',
  properties: {
    prompt: {
      type: 'string',
      description: 'The prompt to use for the generated video',
    },
    image_url: { type: 'string' },
    end_image_url: { anyOf: [{ type: 'string' }, { type: 'null' }] },
    duration: { enum: ['6', '8', '10'], description: 'Duration in seconds' },
    aspect_ratio: {
      enum: ['auto', '16:9', '9:16'],
      description: 'Aspect ratio of the generated video',
    },
    resolution: { enum: ['1080p', '1440p', '2160p'] },
    fps: { enum: ['24', '25', '48', '50'] },
    generate_audio: { type: 'boolean', default: true },
    seed: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
    negative_prompt: { anyOf: [{ type: 'string' }, { type: 'null' }] },
    num_inference_steps: { type: 'integer', minimum: 1, maximum: 50 },
    guidance_scale: { type: 'number' },
  },
  required: ['prompt', 'image_url'],
} as const;

export const zMinimaxHailuo02ImageToVideoInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: 'The text prompt describing the video content to generate',
  }),
  image_url: z.union([z.string(), z.string()]),
  end_image_url: z.union([z.string(), z.unknown()]).optional(),
  prompt_optimizer: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether to enable the model's prompt optimization",
    })
    .optional()
    .default(true),
});

export const MinimaxHailuo02ImageToVideoInputSchema = {
  title: 'MinimaxHailuo02ImageToVideoInput',
  type: 'object',
  properties: {
    prompt: {
      type: 'string',
      description: 'The text prompt describing the video content',
    },
    image_url: { type: 'string' },
    end_image_url: { anyOf: [{ type: 'string' }, { type: 'null' }] },
    prompt_optimizer: { type: 'boolean', default: true },
  },
  required: ['prompt', 'image_url'],
} as const;

export const zBytedanceSeedanceV15ProImageToVideoInput = z.object({
  prompt: z.string().register(z.globalRegistry, {
    description: 'The text prompt used to generate the video',
  }),
  image_url: z.union([z.string(), z.string()]),
  end_image_url: z.union([z.string(), z.unknown()]).optional(),
  aspect_ratio: z
    .enum(['21:9', '16:9', '4:3', '1:1', '3:4', '9:16', 'auto'])
    .register(z.globalRegistry, {
      description: 'The aspect ratio of the generated video',
    })
    .optional(),
  resolution: z
    .enum(['480p', '720p', '1080p'])
    .register(z.globalRegistry, {
      description:
        'Video resolution - 480p for faster generation, 720p for balance, 1080p for higher quality',
    })
    .optional(),
  duration: z
    .enum(['5', '6', '7', '8', '9', '10', '11', '12'])
    .register(z.globalRegistry, {
      description: 'Length of the video in seconds',
    })
    .optional(),
  camera_fixed: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether to fix the camera position',
    })
    .optional()
    .default(false),
  generate_audio: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether to generate audio for the video',
    })
    .optional()
    .default(true),
  enable_safety_checker: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'If set to true, the safety checker will be enabled.',
    })
    .optional()
    .default(true),
  seed: z.union([z.int(), z.unknown()]).optional(),
});

export const BytedanceSeedanceV15ProImageToVideoInputSchema = {
  title: 'BytedanceSeedanceV15ProImageToVideoInput',
  type: 'object',
  properties: {
    prompt: {
      type: 'string',
      description: 'The text prompt used to generate the video',
    },
    image_url: { type: 'string' },
    end_image_url: { anyOf: [{ type: 'string' }, { type: 'null' }] },
    aspect_ratio: {
      enum: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16', 'auto'],
      description: 'The aspect ratio of the generated video',
    },
    resolution: { enum: ['480p', '720p', '1080p'] },
    duration: {
      enum: ['5', '6', '7', '8', '9', '10', '11', '12'],
      description: 'Length of the video in seconds',
    },
    camera_fixed: { type: 'boolean', default: false },
    generate_audio: { type: 'boolean', default: true },
    enable_safety_checker: { type: 'boolean', default: true },
    seed: { anyOf: [{ type: 'integer' }, { type: 'null' }] },
  },
  required: ['prompt', 'image_url'],
} as const;

// ---------------------------------------------------------------------------
// Type union
// ---------------------------------------------------------------------------

export type MotionJSONSchema =
  | typeof GrokImagineVideoImageToVideoInputSchema
  | typeof KlingVideoV3ProImageToVideoInputSchema
  | typeof Veo31ImageToVideoInputSchema
  | typeof Ltx23ImageToVideoInputSchema
  | typeof MinimaxHailuo02ImageToVideoInputSchema
  | typeof BytedanceSeedanceV15ProImageToVideoInputSchema;

// ---------------------------------------------------------------------------
// Runtime maps
// ---------------------------------------------------------------------------

export const MOTION_INPUT_SCHEMAS = {
  'fal-ai/veo3.1/image-to-video': zVeo31ImageToVideoInput,
  'fal-ai/kling-video/v3/pro/image-to-video': zKlingVideoV3ProImageToVideoInput,
  'xai/grok-imagine-video/image-to-video': zGrokImagineVideoImageToVideoInput,
  'fal-ai/ltx-2.3/image-to-video': zLtx23ImageToVideoInput,
  'fal-ai/minimax/hailuo-02/pro/image-to-video':
    zMinimaxHailuo02ImageToVideoInput,
  'fal-ai/bytedance/seedance/v1.5/pro/image-to-video':
    zBytedanceSeedanceV15ProImageToVideoInput,
};

export type MotionEndpointId = keyof typeof MOTION_INPUT_SCHEMAS;

export type MotionInputFor<T extends MotionEndpointId> = z.infer<
  (typeof MOTION_INPUT_SCHEMAS)[T]
>;

export const MOTION_JSON_SCHEMAS = {
  'fal-ai/veo3.1/image-to-video': Veo31ImageToVideoInputSchema,
  'fal-ai/kling-video/v3/pro/image-to-video':
    KlingVideoV3ProImageToVideoInputSchema,
  'xai/grok-imagine-video/image-to-video':
    GrokImagineVideoImageToVideoInputSchema,
  'fal-ai/ltx-2.3/image-to-video': Ltx23ImageToVideoInputSchema,
  'fal-ai/minimax/hailuo-02/pro/image-to-video':
    MinimaxHailuo02ImageToVideoInputSchema,
  'fal-ai/bytedance/seedance/v1.5/pro/image-to-video':
    BytedanceSeedanceV15ProImageToVideoInputSchema,
} satisfies Record<MotionEndpointId, MotionJSONSchema>;

export const MOTION_TRANSFORMS = {
  'fal-ai/veo3.1/image-to-video': motionTransform(
    zVeo31ImageToVideoInput,
    Veo31ImageToVideoInputSchema
  ),
  'fal-ai/kling-video/v3/pro/image-to-video': motionTransform(
    zKlingVideoV3ProImageToVideoInput,
    KlingVideoV3ProImageToVideoInputSchema
  ),
  'xai/grok-imagine-video/image-to-video': motionTransform(
    zGrokImagineVideoImageToVideoInput,
    GrokImagineVideoImageToVideoInputSchema
  ),
  'fal-ai/ltx-2.3/image-to-video': motionTransform(
    zLtx23ImageToVideoInput,
    Ltx23ImageToVideoInputSchema
  ),
  'fal-ai/minimax/hailuo-02/pro/image-to-video': motionTransform(
    zMinimaxHailuo02ImageToVideoInput,
    MinimaxHailuo02ImageToVideoInputSchema
  ),
  'fal-ai/bytedance/seedance/v1.5/pro/image-to-video': motionTransform(
    zBytedanceSeedanceV15ProImageToVideoInput,
    BytedanceSeedanceV15ProImageToVideoInputSchema
  ),
};
