// AUTO-GENERATED by scripts/generate-motion-endpoint-map.ts — do not edit
// Endpoint ID → generated Zod schema and codec mapping for motion models

import { z } from 'zod';

import { motionTransform } from './motion-transform';

import {
  zBytedanceSeedanceV15ProImageToVideoInput,
  zGrokImagineVideoV15ImageToVideoInput,
  zKlingVideoV3ProImageToVideoInput,
  zLtx23ImageToVideoInput,
  zMinimaxHailuo02ProImageToVideoInput,
  zSeedance20ImageToVideoInput,
  zVeo31ImageToVideoInput,
} from './generated/zod.gen';

import {
  BytedanceSeedanceV15ProImageToVideoInputSchema,
  GrokImagineVideoV15ImageToVideoInputSchema,
  KlingVideoV3ProImageToVideoInputSchema,
  Ltx23ImageToVideoInputSchema,
  MinimaxHailuo02ProImageToVideoInputSchema,
  Seedance20ImageToVideoInputSchema,
  Veo31ImageToVideoInputSchema,
} from './generated/schemas.gen';

export type MotionJSONSchema =
  | typeof BytedanceSeedanceV15ProImageToVideoInputSchema
  | typeof GrokImagineVideoV15ImageToVideoInputSchema
  | typeof KlingVideoV3ProImageToVideoInputSchema
  | typeof Ltx23ImageToVideoInputSchema
  | typeof MinimaxHailuo02ProImageToVideoInputSchema
  | typeof Seedance20ImageToVideoInputSchema
  | typeof Veo31ImageToVideoInputSchema;

export const MOTION_INPUT_SCHEMAS = {
  'bytedance/seedance-2.0/image-to-video': zSeedance20ImageToVideoInput,
  'fal-ai/bytedance/seedance/v1.5/pro/image-to-video':
    zBytedanceSeedanceV15ProImageToVideoInput,
  'fal-ai/kling-video/v3/pro/image-to-video': zKlingVideoV3ProImageToVideoInput,
  'fal-ai/ltx-2.3/image-to-video': zLtx23ImageToVideoInput,
  'fal-ai/minimax/hailuo-02/pro/image-to-video':
    zMinimaxHailuo02ProImageToVideoInput,
  'fal-ai/veo3.1/image-to-video': zVeo31ImageToVideoInput,
  'xai/grok-imagine-video/v1.5/image-to-video':
    zGrokImagineVideoV15ImageToVideoInput,
};

export type MotionEndpointId = keyof typeof MOTION_INPUT_SCHEMAS;

/**
 * Input payload for a given motion endpoint. Generated API surface — kept
 * exported even while unused so consumers of new endpoints can adopt it.
 * @public
 */
export type MotionInputFor<T extends MotionEndpointId> = z.infer<
  (typeof MOTION_INPUT_SCHEMAS)[T]
>;

export const MOTION_JSON_SCHEMAS = {
  'bytedance/seedance-2.0/image-to-video': Seedance20ImageToVideoInputSchema,
  'fal-ai/bytedance/seedance/v1.5/pro/image-to-video':
    BytedanceSeedanceV15ProImageToVideoInputSchema,
  'fal-ai/kling-video/v3/pro/image-to-video':
    KlingVideoV3ProImageToVideoInputSchema,
  'fal-ai/ltx-2.3/image-to-video': Ltx23ImageToVideoInputSchema,
  'fal-ai/minimax/hailuo-02/pro/image-to-video':
    MinimaxHailuo02ProImageToVideoInputSchema,
  'fal-ai/veo3.1/image-to-video': Veo31ImageToVideoInputSchema,
  'xai/grok-imagine-video/v1.5/image-to-video':
    GrokImagineVideoV15ImageToVideoInputSchema,
} satisfies Record<MotionEndpointId, MotionJSONSchema>;

export const MOTION_TRANSFORMS = {
  'bytedance/seedance-2.0/image-to-video': motionTransform(
    zSeedance20ImageToVideoInput,
    Seedance20ImageToVideoInputSchema
  ),
  'fal-ai/bytedance/seedance/v1.5/pro/image-to-video': motionTransform(
    zBytedanceSeedanceV15ProImageToVideoInput,
    BytedanceSeedanceV15ProImageToVideoInputSchema
  ),
  'fal-ai/kling-video/v3/pro/image-to-video': motionTransform(
    zKlingVideoV3ProImageToVideoInput,
    KlingVideoV3ProImageToVideoInputSchema
  ),
  'fal-ai/ltx-2.3/image-to-video': motionTransform(
    zLtx23ImageToVideoInput,
    Ltx23ImageToVideoInputSchema
  ),
  'fal-ai/minimax/hailuo-02/pro/image-to-video': motionTransform(
    zMinimaxHailuo02ProImageToVideoInput,
    MinimaxHailuo02ProImageToVideoInputSchema
  ),
  'fal-ai/veo3.1/image-to-video': motionTransform(
    zVeo31ImageToVideoInput,
    Veo31ImageToVideoInputSchema
  ),
  'xai/grok-imagine-video/v1.5/image-to-video': motionTransform(
    zGrokImagineVideoV15ImageToVideoInput,
    GrokImagineVideoV15ImageToVideoInputSchema
  ),
};
