/**
 * Sequence Elements Schema
 * Per-sequence user-uploaded reference images (logos, product shots, screenshots)
 * referenced in scripts by uppercase token.
 */

import {
  type InferInsertModel,
  type InferSelectModel,
  relations,
} from 'drizzle-orm';
import {
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import { generateId } from '../id';
import { sequences } from './sequences';

const VISION_STATUSES = [
  'pending',
  'analyzing',
  'completed',
  'failed',
] as const;
export type ElementVisionStatus = (typeof VISION_STATUSES)[number];

export const sequenceElements = sqliteTable(
  'sequence_elements',
  {
    id: text()
      .$defaultFn(() => generateId())
      .primaryKey()
      .notNull(),
    sequenceId: text('sequence_id')
      .notNull()
      .references(() => sequences.id, { onDelete: 'cascade' }),
    // Original filename as uploaded, used to derive the token.
    uploadedFilename: text('uploaded_filename', { length: 500 }).notNull(),
    // Uppercase token used to reference this element in scripts (e.g. "LOGO", "BOTTLE").
    // Must be unique within a sequence.
    token: text({ length: 100 }).notNull(),
    // Visual description generated by the vision LLM.
    description: text(),
    // Short slug tag used in prompts for consistency (e.g. "red-hex-logo").
    consistencyTag: text('consistency_tag'),
    // Storage
    imageUrl: text('image_url').notNull(),
    imagePath: text('image_path').notNull(), // R2 key
    // Vision analysis status
    visionStatus: text('vision_status')
      .$type<ElementVisionStatus>()
      .default('pending')
      .notNull(),
    visionError: text('vision_error'),
    visionGeneratedAt: integer('vision_generated_at', { mode: 'timestamp' }),
    // First appearance in script (populated during scene-split reconciliation)
    firstMentionSceneId: text('first_mention_scene_id'),
    firstMentionText: text('first_mention_text'),
    firstMentionLine: integer('first_mention_line'),
    // Timestamps
    createdAt: integer('created_at', { mode: 'timestamp' })
      .$defaultFn(() => new Date())
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp' })
      .$defaultFn(() => new Date())
      .notNull(),
  },
  (table) => [
    index('idx_sequence_elements_sequence_id').on(table.sequenceId),
    uniqueIndex('sequence_elements_sequence_token_key').on(
      table.sequenceId,
      table.token
    ),
  ]
);

export const sequenceElementsRelations = relations(
  sequenceElements,
  ({ one }) => ({
    sequence: one(sequences, {
      fields: [sequenceElements.sequenceId],
      references: [sequences.id],
    }),
  })
);

export type SequenceElement = InferSelectModel<typeof sequenceElements>;
export type NewSequenceElement = InferInsertModel<typeof sequenceElements>;

export type SequenceElementMinimal = Pick<
  SequenceElement,
  'id' | 'token' | 'description' | 'imageUrl' | 'consistencyTag'
>;
