/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MetaOgLinkedinRouteImport } from './routes/meta/og-linkedin'
import { Route as MetaOgGithubRouteImport } from './routes/meta/og-github'
import { Route as MetaOgRouteImport } from './routes/meta/og'
import { Route as GiftCodeRouteImport } from './routes/gift/$code'
import { Route as DocsLlmsDotmdRouteImport } from './routes/docs/llms[.]md'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime'
import { Route as ProtectedCreditsRouteImport } from './routes/_protected/credits'
import { Route as MarketingTermsRouteImport } from './routes/_marketing/terms'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing/privacy'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiTestRouteRouteImport } from './routes/api/test/route'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected/settings/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedTalentIndexRouteImport } from './routes/_protected/talent/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedSequencesIndexRouteImport } from './routes/_protected/sequences/index'
import { Route as ProtectedLocationsIndexRouteImport } from './routes/_protected/locations/index'
import { Route as ApiWorkflowsSplatRouteImport } from './routes/api/workflows/$'
import { Route as ApiTestVerifyRouteImport } from './routes/api/test/verify'
import { Route as ApiTestUserRouteImport } from './routes/api/test/user'
import { Route as ApiTestTalentRouteImport } from './routes/api/test/talent'
import { Route as ApiTestStyleRouteImport } from './routes/api/test/style'
import { Route as ApiTestSequenceRouteImport } from './routes/api/test/sequence'
import { Route as ApiTestLocationRouteImport } from './routes/api/test/location'
import { Route as ApiTestImageRouteImport } from './routes/api/test/image'
import { Route as ApiTestFrameRouteImport } from './routes/api/test/frame'
import { Route as ApiTestCleanupRouteImport } from './routes/api/test/cleanup'
import { Route as ApiTestCharacterRouteImport } from './routes/api/test/character'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiOpenrouterCallbackRouteImport } from './routes/api/openrouter/callback'
import { Route as ApiDevMemoryRouteImport } from './routes/api/dev/memory'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedTalentIdRouteImport } from './routes/_protected/talent/$id'
import { Route as ProtectedSettingsPasskeysRouteImport } from './routes/_protected/settings/passkeys'
import { Route as ProtectedSettingsApiKeysRouteImport } from './routes/_protected/settings/api-keys'
import { Route as ProtectedSequencesNewRouteImport } from './routes/_protected/sequences/new'
import { Route as ProtectedLocationsLocationIdRouteImport } from './routes/_protected/locations/$locationId'
import { Route as ProtectedAdminUsageRouteImport } from './routes/_protected/admin/usage'
import { Route as ProtectedSequencesIdRouteRouteImport } from './routes/_protected/sequences/$id/route'
import { Route as ProtectedSequencesIdTheatreRouteImport } from './routes/_protected/sequences/$id/theatre'
import { Route as ProtectedSequencesIdScriptRouteImport } from './routes/_protected/sequences/$id/script'
import { Route as ProtectedSequencesIdScenesRouteImport } from './routes/_protected/sequences/$id/scenes'
import { Route as ProtectedSequencesIdMusicRouteImport } from './routes/_protected/sequences/$id/music'
import { Route as ProtectedSequencesIdElementsRouteImport } from './routes/_protected/sequences/$id/elements'
import { Route as ProtectedSequencesIdLocationsIndexRouteImport } from './routes/_protected/sequences/$id/locations/index'
import { Route as ProtectedSequencesIdCastIndexRouteImport } from './routes/_protected/sequences/$id/cast/index'
import { Route as ProtectedSequencesIdLocationsLocationIdRouteImport } from './routes/_protected/sequences/$id/locations/$locationId'
import { Route as ProtectedSequencesIdCastCharacterIdRouteImport } from './routes/_protected/sequences/$id/cast/$characterId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MetaOgLinkedinRoute = MetaOgLinkedinRouteImport.update({
  id: '/meta/og-linkedin',
  path: '/meta/og-linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaOgGithubRoute = MetaOgGithubRouteImport.update({
  id: '/meta/og-github',
  path: '/meta/og-github',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaOgRoute = MetaOgRouteImport.update({
  id: '/meta/og',
  path: '/meta/og',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCodeRoute = GiftCodeRouteImport.update({
  id: '/gift/$code',
  path: '/gift/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsDotmdRoute = DocsLlmsDotmdRouteImport.update({
  id: '/llms.md',
  path: '/llms.md',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCreditsRoute = ProtectedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiTestRouteRoute = ApiTestRouteRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTalentIndexRoute = ProtectedTalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedSequencesIndexRoute = ProtectedSequencesIndexRouteImport.update({
  id: '/sequences/',
  path: '/sequences/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLocationsIndexRoute = ProtectedLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiWorkflowsSplatRoute = ApiWorkflowsSplatRouteImport.update({
  id: '/api/workflows/$',
  path: '/api/workflows/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestVerifyRoute = ApiTestVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestUserRoute = ApiTestUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestTalentRoute = ApiTestTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestStyleRoute = ApiTestStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestSequenceRoute = ApiTestSequenceRouteImport.update({
  id: '/sequence',
  path: '/sequence',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestLocationRoute = ApiTestLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestImageRoute = ApiTestImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestFrameRoute = ApiTestFrameRouteImport.update({
  id: '/frame',
  path: '/frame',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestCleanupRoute = ApiTestCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiTestCharacterRoute = ApiTestCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => ApiTestRouteRoute,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterCallbackRoute = ApiOpenrouterCallbackRouteImport.update({
  id: '/api/openrouter/callback',
  path: '/api/openrouter/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevMemoryRoute = ApiDevMemoryRouteImport.update({
  id: '/api/dev/memory',
  path: '/api/dev/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTalentIdRoute = ProtectedTalentIdRouteImport.update({
  id: '/talent/$id',
  path: '/talent/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsPasskeysRoute =
  ProtectedSettingsPasskeysRouteImport.update({
    id: '/passkeys',
    path: '/passkeys',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsApiKeysRoute =
  ProtectedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSequencesNewRoute = ProtectedSequencesNewRouteImport.update({
  id: '/sequences/new',
  path: '/sequences/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLocationsLocationIdRoute =
  ProtectedLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAdminUsageRoute = ProtectedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedSequencesIdRouteRoute =
  ProtectedSequencesIdRouteRouteImport.update({
    id: '/sequences/$id',
    path: '/sequences/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSequencesIdTheatreRoute =
  ProtectedSequencesIdTheatreRouteImport.update({
    id: '/theatre',
    path: '/theatre',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)
const ProtectedSequencesIdScriptRoute =
  ProtectedSequencesIdScriptRouteImport.update({
    id: '/script',
    path: '/script',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)
const ProtectedSequencesIdScenesRoute =
  ProtectedSequencesIdScenesRouteImport.update({
    id: '/scenes',
    path: '/scenes',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)
const ProtectedSequencesIdMusicRoute =
  ProtectedSequencesIdMusicRouteImport.update({
    id: '/music',
    path: '/music',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)
const ProtectedSequencesIdElementsRoute =
  ProtectedSequencesIdElementsRouteImport.update({
    id: '/elements',
    path: '/elements',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)
const ProtectedSequencesIdLocationsIndexRoute =
  ProtectedSequencesIdLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)
const ProtectedSequencesIdCastIndexRoute =
  ProtectedSequencesIdCastIndexRouteImport.update({
    id: '/cast/',
    path: '/cast/',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)
const ProtectedSequencesIdLocationsLocationIdRoute =
  ProtectedSequencesIdLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)
const ProtectedSequencesIdCastCharacterIdRoute =
  ProtectedSequencesIdCastCharacterIdRouteImport.update({
    id: '/cast/$characterId',
    path: '/cast/$characterId',
    getParentRoute: () => ProtectedSequencesIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/api/test': typeof ApiTestRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/verify': typeof AuthVerifyRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/terms': typeof MarketingTermsRoute
  '/credits': typeof ProtectedCreditsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.md': typeof DocsLlmsDotmdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/meta/og': typeof MetaOgRoute
  '/meta/og-github': typeof MetaOgGithubRoute
  '/meta/og-linkedin': typeof MetaOgLinkedinRoute
  '/docs/': typeof DocsIndexRoute
  '/sequences/$id': typeof ProtectedSequencesIdRouteRouteWithChildren
  '/admin/usage': typeof ProtectedAdminUsageRoute
  '/locations/$locationId': typeof ProtectedLocationsLocationIdRoute
  '/sequences/new': typeof ProtectedSequencesNewRoute
  '/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/settings/passkeys': typeof ProtectedSettingsPasskeysRoute
  '/talent/$id': typeof ProtectedTalentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/dev/memory': typeof ApiDevMemoryRoute
  '/api/openrouter/callback': typeof ApiOpenrouterCallbackRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/test/character': typeof ApiTestCharacterRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/frame': typeof ApiTestFrameRoute
  '/api/test/image': typeof ApiTestImageRoute
  '/api/test/location': typeof ApiTestLocationRoute
  '/api/test/sequence': typeof ApiTestSequenceRoute
  '/api/test/style': typeof ApiTestStyleRoute
  '/api/test/talent': typeof ApiTestTalentRoute
  '/api/test/user': typeof ApiTestUserRoute
  '/api/test/verify': typeof ApiTestVerifyRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
  '/locations/': typeof ProtectedLocationsIndexRoute
  '/sequences/': typeof ProtectedSequencesIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/talent/': typeof ProtectedTalentIndexRoute
  '/sequences/$id/elements': typeof ProtectedSequencesIdElementsRoute
  '/sequences/$id/music': typeof ProtectedSequencesIdMusicRoute
  '/sequences/$id/scenes': typeof ProtectedSequencesIdScenesRoute
  '/sequences/$id/script': typeof ProtectedSequencesIdScriptRoute
  '/sequences/$id/theatre': typeof ProtectedSequencesIdTheatreRoute
  '/sequences/$id/cast/$characterId': typeof ProtectedSequencesIdCastCharacterIdRoute
  '/sequences/$id/locations/$locationId': typeof ProtectedSequencesIdLocationsLocationIdRoute
  '/sequences/$id/cast/': typeof ProtectedSequencesIdCastIndexRoute
  '/sequences/$id/locations/': typeof ProtectedSequencesIdLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/api/test': typeof ApiTestRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/verify': typeof AuthVerifyRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/terms': typeof MarketingTermsRoute
  '/credits': typeof ProtectedCreditsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.md': typeof DocsLlmsDotmdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/meta/og': typeof MetaOgRoute
  '/meta/og-github': typeof MetaOgGithubRoute
  '/meta/og-linkedin': typeof MetaOgLinkedinRoute
  '/docs': typeof DocsIndexRoute
  '/sequences/$id': typeof ProtectedSequencesIdRouteRouteWithChildren
  '/admin/usage': typeof ProtectedAdminUsageRoute
  '/locations/$locationId': typeof ProtectedLocationsLocationIdRoute
  '/sequences/new': typeof ProtectedSequencesNewRoute
  '/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/settings/passkeys': typeof ProtectedSettingsPasskeysRoute
  '/talent/$id': typeof ProtectedTalentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/dev/memory': typeof ApiDevMemoryRoute
  '/api/openrouter/callback': typeof ApiOpenrouterCallbackRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/test/character': typeof ApiTestCharacterRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/frame': typeof ApiTestFrameRoute
  '/api/test/image': typeof ApiTestImageRoute
  '/api/test/location': typeof ApiTestLocationRoute
  '/api/test/sequence': typeof ApiTestSequenceRoute
  '/api/test/style': typeof ApiTestStyleRoute
  '/api/test/talent': typeof ApiTestTalentRoute
  '/api/test/user': typeof ApiTestUserRoute
  '/api/test/verify': typeof ApiTestVerifyRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
  '/locations': typeof ProtectedLocationsIndexRoute
  '/sequences': typeof ProtectedSequencesIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/talent': typeof ProtectedTalentIndexRoute
  '/sequences/$id/elements': typeof ProtectedSequencesIdElementsRoute
  '/sequences/$id/music': typeof ProtectedSequencesIdMusicRoute
  '/sequences/$id/scenes': typeof ProtectedSequencesIdScenesRoute
  '/sequences/$id/script': typeof ProtectedSequencesIdScriptRoute
  '/sequences/$id/theatre': typeof ProtectedSequencesIdTheatreRoute
  '/sequences/$id/cast/$characterId': typeof ProtectedSequencesIdCastCharacterIdRoute
  '/sequences/$id/locations/$locationId': typeof ProtectedSequencesIdLocationsLocationIdRoute
  '/sequences/$id/cast': typeof ProtectedSequencesIdCastIndexRoute
  '/sequences/$id/locations': typeof ProtectedSequencesIdLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/api/test': typeof ApiTestRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/_protected/credits': typeof ProtectedCreditsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.md': typeof DocsLlmsDotmdRoute
  '/gift/$code': typeof GiftCodeRoute
  '/meta/og': typeof MetaOgRoute
  '/meta/og-github': typeof MetaOgGithubRoute
  '/meta/og-linkedin': typeof MetaOgLinkedinRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_protected/sequences/$id': typeof ProtectedSequencesIdRouteRouteWithChildren
  '/_protected/admin/usage': typeof ProtectedAdminUsageRoute
  '/_protected/locations/$locationId': typeof ProtectedLocationsLocationIdRoute
  '/_protected/sequences/new': typeof ProtectedSequencesNewRoute
  '/_protected/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/_protected/settings/passkeys': typeof ProtectedSettingsPasskeysRoute
  '/_protected/talent/$id': typeof ProtectedTalentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/dev/memory': typeof ApiDevMemoryRoute
  '/api/openrouter/callback': typeof ApiOpenrouterCallbackRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/test/character': typeof ApiTestCharacterRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/frame': typeof ApiTestFrameRoute
  '/api/test/image': typeof ApiTestImageRoute
  '/api/test/location': typeof ApiTestLocationRoute
  '/api/test/sequence': typeof ApiTestSequenceRoute
  '/api/test/style': typeof ApiTestStyleRoute
  '/api/test/talent': typeof ApiTestTalentRoute
  '/api/test/user': typeof ApiTestUserRoute
  '/api/test/verify': typeof ApiTestVerifyRoute
  '/api/workflows/$': typeof ApiWorkflowsSplatRoute
  '/_protected/locations/': typeof ProtectedLocationsIndexRoute
  '/_protected/sequences/': typeof ProtectedSequencesIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/talent/': typeof ProtectedTalentIndexRoute
  '/_protected/sequences/$id/elements': typeof ProtectedSequencesIdElementsRoute
  '/_protected/sequences/$id/music': typeof ProtectedSequencesIdMusicRoute
  '/_protected/sequences/$id/scenes': typeof ProtectedSequencesIdScenesRoute
  '/_protected/sequences/$id/script': typeof ProtectedSequencesIdScriptRoute
  '/_protected/sequences/$id/theatre': typeof ProtectedSequencesIdTheatreRoute
  '/_protected/sequences/$id/cast/$characterId': typeof ProtectedSequencesIdCastCharacterIdRoute
  '/_protected/sequences/$id/locations/$locationId': typeof ProtectedSequencesIdLocationsLocationIdRoute
  '/_protected/sequences/$id/cast/': typeof ProtectedSequencesIdCastIndexRoute
  '/_protected/sequences/$id/locations/': typeof ProtectedSequencesIdLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/settings'
    | '/api/test'
    | '/login'
    | '/verify'
    | '/privacy'
    | '/terms'
    | '/credits'
    | '/api/realtime'
    | '/docs/$'
    | '/docs/llms.md'
    | '/gift/$code'
    | '/meta/og'
    | '/meta/og-github'
    | '/meta/og-linkedin'
    | '/docs/'
    | '/sequences/$id'
    | '/admin/usage'
    | '/locations/$locationId'
    | '/sequences/new'
    | '/settings/api-keys'
    | '/settings/passkeys'
    | '/talent/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/dev/memory'
    | '/api/openrouter/callback'
    | '/api/storage/upload'
    | '/api/test/character'
    | '/api/test/cleanup'
    | '/api/test/frame'
    | '/api/test/image'
    | '/api/test/location'
    | '/api/test/sequence'
    | '/api/test/style'
    | '/api/test/talent'
    | '/api/test/user'
    | '/api/test/verify'
    | '/api/workflows/$'
    | '/locations/'
    | '/sequences/'
    | '/settings/'
    | '/talent/'
    | '/sequences/$id/elements'
    | '/sequences/$id/music'
    | '/sequences/$id/scenes'
    | '/sequences/$id/script'
    | '/sequences/$id/theatre'
    | '/sequences/$id/cast/$characterId'
    | '/sequences/$id/locations/$locationId'
    | '/sequences/$id/cast/'
    | '/sequences/$id/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/api/test'
    | '/login'
    | '/verify'
    | '/privacy'
    | '/terms'
    | '/credits'
    | '/api/realtime'
    | '/docs/$'
    | '/docs/llms.md'
    | '/gift/$code'
    | '/meta/og'
    | '/meta/og-github'
    | '/meta/og-linkedin'
    | '/docs'
    | '/sequences/$id'
    | '/admin/usage'
    | '/locations/$locationId'
    | '/sequences/new'
    | '/settings/api-keys'
    | '/settings/passkeys'
    | '/talent/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/dev/memory'
    | '/api/openrouter/callback'
    | '/api/storage/upload'
    | '/api/test/character'
    | '/api/test/cleanup'
    | '/api/test/frame'
    | '/api/test/image'
    | '/api/test/location'
    | '/api/test/sequence'
    | '/api/test/style'
    | '/api/test/talent'
    | '/api/test/user'
    | '/api/test/verify'
    | '/api/workflows/$'
    | '/locations'
    | '/sequences'
    | '/settings'
    | '/talent'
    | '/sequences/$id/elements'
    | '/sequences/$id/music'
    | '/sequences/$id/scenes'
    | '/sequences/$id/script'
    | '/sequences/$id/theatre'
    | '/sequences/$id/cast/$characterId'
    | '/sequences/$id/locations/$locationId'
    | '/sequences/$id/cast'
    | '/sequences/$id/locations'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_marketing'
    | '/docs'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_protected/admin'
    | '/_protected/settings'
    | '/api/test'
    | '/_auth/login'
    | '/_auth/verify'
    | '/_marketing/privacy'
    | '/_marketing/terms'
    | '/_protected/credits'
    | '/api/realtime'
    | '/docs/$'
    | '/docs/llms.md'
    | '/gift/$code'
    | '/meta/og'
    | '/meta/og-github'
    | '/meta/og-linkedin'
    | '/_marketing/'
    | '/docs/'
    | '/_protected/sequences/$id'
    | '/_protected/admin/usage'
    | '/_protected/locations/$locationId'
    | '/_protected/sequences/new'
    | '/_protected/settings/api-keys'
    | '/_protected/settings/passkeys'
    | '/_protected/talent/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/dev/memory'
    | '/api/openrouter/callback'
    | '/api/storage/upload'
    | '/api/test/character'
    | '/api/test/cleanup'
    | '/api/test/frame'
    | '/api/test/image'
    | '/api/test/location'
    | '/api/test/sequence'
    | '/api/test/style'
    | '/api/test/talent'
    | '/api/test/user'
    | '/api/test/verify'
    | '/api/workflows/$'
    | '/_protected/locations/'
    | '/_protected/sequences/'
    | '/_protected/settings/'
    | '/_protected/talent/'
    | '/_protected/sequences/$id/elements'
    | '/_protected/sequences/$id/music'
    | '/_protected/sequences/$id/scenes'
    | '/_protected/sequences/$id/script'
    | '/_protected/sequences/$id/theatre'
    | '/_protected/sequences/$id/cast/$characterId'
    | '/_protected/sequences/$id/locations/$locationId'
    | '/_protected/sequences/$id/cast/'
    | '/_protected/sequences/$id/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiTestRouteRoute: typeof ApiTestRouteRouteWithChildren
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  GiftCodeRoute: typeof GiftCodeRoute
  MetaOgRoute: typeof MetaOgRoute
  MetaOgGithubRoute: typeof MetaOgGithubRoute
  MetaOgLinkedinRoute: typeof MetaOgLinkedinRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiDevMemoryRoute: typeof ApiDevMemoryRoute
  ApiOpenrouterCallbackRoute: typeof ApiOpenrouterCallbackRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiWorkflowsSplatRoute: typeof ApiWorkflowsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/meta/og-linkedin': {
      id: '/meta/og-linkedin'
      path: '/meta/og-linkedin'
      fullPath: '/meta/og-linkedin'
      preLoaderRoute: typeof MetaOgLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/og-github': {
      id: '/meta/og-github'
      path: '/meta/og-github'
      fullPath: '/meta/og-github'
      preLoaderRoute: typeof MetaOgGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta/og': {
      id: '/meta/og'
      path: '/meta/og'
      fullPath: '/meta/og'
      preLoaderRoute: typeof MetaOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/$code': {
      id: '/gift/$code'
      path: '/gift/$code'
      fullPath: '/gift/$code'
      preLoaderRoute: typeof GiftCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms.md': {
      id: '/docs/llms.md'
      path: '/llms.md'
      fullPath: '/docs/llms.md'
      preLoaderRoute: typeof DocsLlmsDotmdRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/credits': {
      id: '/_protected/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof ProtectedCreditsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/talent/': {
      id: '/_protected/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof ProtectedTalentIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/sequences/': {
      id: '/_protected/sequences/'
      path: '/sequences'
      fullPath: '/sequences/'
      preLoaderRoute: typeof ProtectedSequencesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/locations/': {
      id: '/_protected/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof ProtectedLocationsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/workflows/$': {
      id: '/api/workflows/$'
      path: '/api/workflows/$'
      fullPath: '/api/workflows/$'
      preLoaderRoute: typeof ApiWorkflowsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/verify': {
      id: '/api/test/verify'
      path: '/verify'
      fullPath: '/api/test/verify'
      preLoaderRoute: typeof ApiTestVerifyRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/user': {
      id: '/api/test/user'
      path: '/user'
      fullPath: '/api/test/user'
      preLoaderRoute: typeof ApiTestUserRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/talent': {
      id: '/api/test/talent'
      path: '/talent'
      fullPath: '/api/test/talent'
      preLoaderRoute: typeof ApiTestTalentRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/style': {
      id: '/api/test/style'
      path: '/style'
      fullPath: '/api/test/style'
      preLoaderRoute: typeof ApiTestStyleRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/sequence': {
      id: '/api/test/sequence'
      path: '/sequence'
      fullPath: '/api/test/sequence'
      preLoaderRoute: typeof ApiTestSequenceRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/location': {
      id: '/api/test/location'
      path: '/location'
      fullPath: '/api/test/location'
      preLoaderRoute: typeof ApiTestLocationRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/image': {
      id: '/api/test/image'
      path: '/image'
      fullPath: '/api/test/image'
      preLoaderRoute: typeof ApiTestImageRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/frame': {
      id: '/api/test/frame'
      path: '/frame'
      fullPath: '/api/test/frame'
      preLoaderRoute: typeof ApiTestFrameRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/cleanup': {
      id: '/api/test/cleanup'
      path: '/cleanup'
      fullPath: '/api/test/cleanup'
      preLoaderRoute: typeof ApiTestCleanupRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/test/character': {
      id: '/api/test/character'
      path: '/character'
      fullPath: '/api/test/character'
      preLoaderRoute: typeof ApiTestCharacterRouteImport
      parentRoute: typeof ApiTestRouteRoute
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter/callback': {
      id: '/api/openrouter/callback'
      path: '/api/openrouter/callback'
      fullPath: '/api/openrouter/callback'
      preLoaderRoute: typeof ApiOpenrouterCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/memory': {
      id: '/api/dev/memory'
      path: '/api/dev/memory'
      fullPath: '/api/dev/memory'
      preLoaderRoute: typeof ApiDevMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/talent/$id': {
      id: '/_protected/talent/$id'
      path: '/talent/$id'
      fullPath: '/talent/$id'
      preLoaderRoute: typeof ProtectedTalentIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/passkeys': {
      id: '/_protected/settings/passkeys'
      path: '/passkeys'
      fullPath: '/settings/passkeys'
      preLoaderRoute: typeof ProtectedSettingsPasskeysRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/api-keys': {
      id: '/_protected/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof ProtectedSettingsApiKeysRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/sequences/new': {
      id: '/_protected/sequences/new'
      path: '/sequences/new'
      fullPath: '/sequences/new'
      preLoaderRoute: typeof ProtectedSequencesNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/locations/$locationId': {
      id: '/_protected/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof ProtectedLocationsLocationIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/usage': {
      id: '/_protected/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof ProtectedAdminUsageRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/sequences/$id': {
      id: '/_protected/sequences/$id'
      path: '/sequences/$id'
      fullPath: '/sequences/$id'
      preLoaderRoute: typeof ProtectedSequencesIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sequences/$id/theatre': {
      id: '/_protected/sequences/$id/theatre'
      path: '/theatre'
      fullPath: '/sequences/$id/theatre'
      preLoaderRoute: typeof ProtectedSequencesIdTheatreRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
    '/_protected/sequences/$id/script': {
      id: '/_protected/sequences/$id/script'
      path: '/script'
      fullPath: '/sequences/$id/script'
      preLoaderRoute: typeof ProtectedSequencesIdScriptRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
    '/_protected/sequences/$id/scenes': {
      id: '/_protected/sequences/$id/scenes'
      path: '/scenes'
      fullPath: '/sequences/$id/scenes'
      preLoaderRoute: typeof ProtectedSequencesIdScenesRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
    '/_protected/sequences/$id/music': {
      id: '/_protected/sequences/$id/music'
      path: '/music'
      fullPath: '/sequences/$id/music'
      preLoaderRoute: typeof ProtectedSequencesIdMusicRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
    '/_protected/sequences/$id/elements': {
      id: '/_protected/sequences/$id/elements'
      path: '/elements'
      fullPath: '/sequences/$id/elements'
      preLoaderRoute: typeof ProtectedSequencesIdElementsRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
    '/_protected/sequences/$id/locations/': {
      id: '/_protected/sequences/$id/locations/'
      path: '/locations'
      fullPath: '/sequences/$id/locations/'
      preLoaderRoute: typeof ProtectedSequencesIdLocationsIndexRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
    '/_protected/sequences/$id/cast/': {
      id: '/_protected/sequences/$id/cast/'
      path: '/cast'
      fullPath: '/sequences/$id/cast/'
      preLoaderRoute: typeof ProtectedSequencesIdCastIndexRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
    '/_protected/sequences/$id/locations/$locationId': {
      id: '/_protected/sequences/$id/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/sequences/$id/locations/$locationId'
      preLoaderRoute: typeof ProtectedSequencesIdLocationsLocationIdRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
    '/_protected/sequences/$id/cast/$characterId': {
      id: '/_protected/sequences/$id/cast/$characterId'
      path: '/cast/$characterId'
      fullPath: '/sequences/$id/cast/$characterId'
      preLoaderRoute: typeof ProtectedSequencesIdCastCharacterIdRouteImport
      parentRoute: typeof ProtectedSequencesIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminUsageRoute: typeof ProtectedAdminUsageRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminUsageRoute: ProtectedAdminUsageRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsApiKeysRoute: typeof ProtectedSettingsApiKeysRoute
  ProtectedSettingsPasskeysRoute: typeof ProtectedSettingsPasskeysRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsApiKeysRoute: ProtectedSettingsApiKeysRoute,
    ProtectedSettingsPasskeysRoute: ProtectedSettingsPasskeysRoute,
    ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedSequencesIdRouteRouteChildren {
  ProtectedSequencesIdElementsRoute: typeof ProtectedSequencesIdElementsRoute
  ProtectedSequencesIdMusicRoute: typeof ProtectedSequencesIdMusicRoute
  ProtectedSequencesIdScenesRoute: typeof ProtectedSequencesIdScenesRoute
  ProtectedSequencesIdScriptRoute: typeof ProtectedSequencesIdScriptRoute
  ProtectedSequencesIdTheatreRoute: typeof ProtectedSequencesIdTheatreRoute
  ProtectedSequencesIdCastCharacterIdRoute: typeof ProtectedSequencesIdCastCharacterIdRoute
  ProtectedSequencesIdLocationsLocationIdRoute: typeof ProtectedSequencesIdLocationsLocationIdRoute
  ProtectedSequencesIdCastIndexRoute: typeof ProtectedSequencesIdCastIndexRoute
  ProtectedSequencesIdLocationsIndexRoute: typeof ProtectedSequencesIdLocationsIndexRoute
}

const ProtectedSequencesIdRouteRouteChildren: ProtectedSequencesIdRouteRouteChildren =
  {
    ProtectedSequencesIdElementsRoute: ProtectedSequencesIdElementsRoute,
    ProtectedSequencesIdMusicRoute: ProtectedSequencesIdMusicRoute,
    ProtectedSequencesIdScenesRoute: ProtectedSequencesIdScenesRoute,
    ProtectedSequencesIdScriptRoute: ProtectedSequencesIdScriptRoute,
    ProtectedSequencesIdTheatreRoute: ProtectedSequencesIdTheatreRoute,
    ProtectedSequencesIdCastCharacterIdRoute:
      ProtectedSequencesIdCastCharacterIdRoute,
    ProtectedSequencesIdLocationsLocationIdRoute:
      ProtectedSequencesIdLocationsLocationIdRoute,
    ProtectedSequencesIdCastIndexRoute: ProtectedSequencesIdCastIndexRoute,
    ProtectedSequencesIdLocationsIndexRoute:
      ProtectedSequencesIdLocationsIndexRoute,
  }

const ProtectedSequencesIdRouteRouteWithChildren =
  ProtectedSequencesIdRouteRoute._addFileChildren(
    ProtectedSequencesIdRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedCreditsRoute: typeof ProtectedCreditsRoute
  ProtectedSequencesIdRouteRoute: typeof ProtectedSequencesIdRouteRouteWithChildren
  ProtectedLocationsLocationIdRoute: typeof ProtectedLocationsLocationIdRoute
  ProtectedSequencesNewRoute: typeof ProtectedSequencesNewRoute
  ProtectedTalentIdRoute: typeof ProtectedTalentIdRoute
  ProtectedLocationsIndexRoute: typeof ProtectedLocationsIndexRoute
  ProtectedSequencesIndexRoute: typeof ProtectedSequencesIndexRoute
  ProtectedTalentIndexRoute: typeof ProtectedTalentIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedCreditsRoute: ProtectedCreditsRoute,
  ProtectedSequencesIdRouteRoute: ProtectedSequencesIdRouteRouteWithChildren,
  ProtectedLocationsLocationIdRoute: ProtectedLocationsLocationIdRoute,
  ProtectedSequencesNewRoute: ProtectedSequencesNewRoute,
  ProtectedTalentIdRoute: ProtectedTalentIdRoute,
  ProtectedLocationsIndexRoute: ProtectedLocationsIndexRoute,
  ProtectedSequencesIndexRoute: ProtectedSequencesIndexRoute,
  ProtectedTalentIndexRoute: ProtectedTalentIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface MarketingRouteChildren {
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsLlmsDotmdRoute: typeof DocsLlmsDotmdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsLlmsDotmdRoute: DocsLlmsDotmdRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ApiTestRouteRouteChildren {
  ApiTestCharacterRoute: typeof ApiTestCharacterRoute
  ApiTestCleanupRoute: typeof ApiTestCleanupRoute
  ApiTestFrameRoute: typeof ApiTestFrameRoute
  ApiTestImageRoute: typeof ApiTestImageRoute
  ApiTestLocationRoute: typeof ApiTestLocationRoute
  ApiTestSequenceRoute: typeof ApiTestSequenceRoute
  ApiTestStyleRoute: typeof ApiTestStyleRoute
  ApiTestTalentRoute: typeof ApiTestTalentRoute
  ApiTestUserRoute: typeof ApiTestUserRoute
  ApiTestVerifyRoute: typeof ApiTestVerifyRoute
}

const ApiTestRouteRouteChildren: ApiTestRouteRouteChildren = {
  ApiTestCharacterRoute: ApiTestCharacterRoute,
  ApiTestCleanupRoute: ApiTestCleanupRoute,
  ApiTestFrameRoute: ApiTestFrameRoute,
  ApiTestImageRoute: ApiTestImageRoute,
  ApiTestLocationRoute: ApiTestLocationRoute,
  ApiTestSequenceRoute: ApiTestSequenceRoute,
  ApiTestStyleRoute: ApiTestStyleRoute,
  ApiTestTalentRoute: ApiTestTalentRoute,
  ApiTestUserRoute: ApiTestUserRoute,
  ApiTestVerifyRoute: ApiTestVerifyRoute,
}

const ApiTestRouteRouteWithChildren = ApiTestRouteRoute._addFileChildren(
  ApiTestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiTestRouteRoute: ApiTestRouteRouteWithChildren,
  ApiRealtimeRoute: ApiRealtimeRoute,
  GiftCodeRoute: GiftCodeRoute,
  MetaOgRoute: MetaOgRoute,
  MetaOgGithubRoute: MetaOgGithubRoute,
  MetaOgLinkedinRoute: MetaOgLinkedinRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiDevMemoryRoute: ApiDevMemoryRoute,
  ApiOpenrouterCallbackRoute: ApiOpenrouterCallbackRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiWorkflowsSplatRoute: ApiWorkflowsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
